# This file is managed by 'repo_helper'. Don't edit it directly.
---
name: "Docs Check"
on:
  - pull_request
  - push

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: "actions/checkout@v1"
      - name: Install and Build ğŸ”§
        uses: ammaraskar/sphinx-action@master
        with:
          pre-build-command: apt-get update && apt-get install gcc python3-dev git pandoc libcairo2-dev pkg-config python3-dev libgirepository1.0-dev -y && python -m pip install tox
          docs-folder: "doc-source/"
          build-command: "tox -e docs -- "
